---
- name: Creates App Database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present

    login_user: '{{ mysql_root_username }}'
    login_password: '{{ mysql_root_password }}'
    login_unix_socket: /var/run/mysqld/mysqld.sock
