- name: Install MariaDB
  block:
    - name: Install mariadb
      apt:
        name: mariadb-server
        state: latest

    - name: Install mariadb
      apt:
        name: mariadb-client
        state: latest
