---
- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Install Node.js from Ubuntu repository
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install npm from Ubuntu repository
  apt:
    name: npm
    state: present
    update_cache: yes

- name: Add Yarn GPG key
  shell: |
    curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarn.gpg
  args:
    creates: /usr/share/keyrings/yarn.gpg

- name: Add Yarn repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn
    state: present
    update_cache: yes

- name: Install Yarn
  apt:
    name: yarn
    state: present
    update_cache: yes
