---
- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Get Ubuntu codename
  set_fact:
    ubuntu_codename: "{{ ansible_distribution_release }}"

- name: Set Node.js repository based on Ubuntu version
  set_fact:
    nodejs_repo: "{{ 'deb https://deb.nodesource.com/node_' + node_version + '.x ' + ubuntu_codename + ' main' if ubuntu_codename in ['jammy', 'focal', 'bionic'] else 'deb https://deb.nodesource.com/node_' + node_version + '.x jammy main' }}"

- name: Add NodeSource GPG key
  shell: |
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
  args:
    creates: /usr/share/keyrings/nodesource.gpg

- name: Add NodeSource repository
  apt_repository:
    repo: "{{ nodejs_repo }}"
    filename: nodesource
    state: present
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Add Yarn GPG key
  shell: |
    curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarn.gpg
  args:
    creates: /usr/share/keyrings/yarn.gpg

- name: Add Yarn repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn
    state: present
    update_cache: yes

- name: Install Yarn
  apt:
    name: yarn
    state: present
    update_cache: yes
