---
- name: Set the correct opcache filename (Ubuntu/Debian).
  set_fact:
    php_opcache_conf_filename: "10-opcache.ini"

- name: Ensure dirmngr is installed (gnupg dependency).
  apt:
    name: dirmngr
    state: present

- name: Add repository for PHP versions (Ubuntu).
  block:
    - name: Add Ondrej Surý PPA GPG key for Ubuntu
      shell: |
        curl -fsSL https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C | gpg --dearmor -o /usr/share/keyrings/ondrej-php.gpg
      args:
        creates: /usr/share/keyrings/ondrej-php.gpg
      
    - name: Add Ondrej Surý PPA repository for Ubuntu
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/ondrej-php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main"
        filename: ondrej-php
        state: present
        update_cache: yes
  when: ansible_distribution == "Ubuntu"

# Debian-specific tasks.
- name: Add dependencies for PHP versions (Debian).
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
  when: ansible_distribution == "Debian"

- name: Add Ondrej Sury's GPG key (Debian).
  shell: |
    curl -fsSL https://packages.sury.org/php/apt.gpg | gpg --dearmor -o /usr/share/keyrings/ondrej-php-debian.gpg
  args:
    creates: /usr/share/keyrings/ondrej-php-debian.gpg
  when: ansible_distribution == "Debian"

- name: Add Ondrej Sury's repo (Debian).
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/ondrej-php-debian.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    filename: ondrej-php-debian
    state: present
  register: php_ondrej_debian_repo
  when: ansible_distribution == "Debian"

- name: Update apt caches after repo is added (Debian).
  apt: update_cache=true
  when:
    - php_ondrej_debian_repo.changed
    - ansible_distribution == "Debian"
  tags: ['skip_ansible_lint']

- name: Purge PHP version packages (besides the currently chosen php_version).
  apt:
    name: "{{ php_versions_debian | reject('search', 'php' ~ php_version) | list }}"
    state: absent
    purge: true
    force: true
  register: php_version_purge

- name: Also purge php-common package if any versions were just purged.
  apt:
    name: php-common
    state: absent
    purge: true
    force: true
  when: php_version_purge.changed | bool
